//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvBilgileri
    {
        public int Id { get; set; }
        public int KacOdalı { get; set; }
        public bool DogalGazlımı { get; set; }
        public int Kira { get; set; }
        public string Adres { get; set; }
        public bool Esyalımı { get; set; }
        public bool DepozitoVarmı { get; set; }
    }
}
