//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaturaBilgisi
    {
        public int Id { get; set; }
        public int MusteriBilgileriId { get; set; }
        public int EvMaliyetId { get; set; }
        public string donemNo { get; set; }
    }
}
