//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class MalzemeListesi
    {
        public int Id { get; set; }
        public string MalzemeAdi { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<double> kilo { get; set; }
        public Nullable<int> kalite { get; set; }
    }
}
