//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvTakip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvTakipEntities1 : DbContext
    {
        public EvTakipEntities1()
            : base("name=EvTakipEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EvBilgileri> EvBilgileri { get; set; }
        public virtual DbSet<EvMaliyet> EvMaliyet { get; set; }
        public virtual DbSet<FaturaBilgisi> FaturaBilgisi { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<MalzemeListesi> MalzemeListesi { get; set; }
        public virtual DbSet<MusteriBilgileri> MusteriBilgileri { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
