//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriBilgileri
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string TcKimlikNo { get; set; }
        public string Telefon { get; set; }
        public string Sehir { get; set; }
        public string Eposta { get; set; }
        public int evBilgiId { get; set; }
    }
}
